server:
  port: 8512

spring:
  main:
    web-application-type: reactive
  application:
    name: service-user
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.76.100:8848
    sentinel:
      transport:
        dashboard: localhost:8080
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.76.100:3306/db_spzx?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=true
    username: root
    password: 123456
  data:
    redis:
      host: 192.168.76.100
      port: 6379
      password: 1234

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*/*.xml
